[shaders]
text.fragment = "res/text.f.glsl"
text.vertex = "res/text.v.glsl"
triangle.fragment = "res/triangle.f.glsl"
triangle.vertex = "res/triangle.v.glsl"
sprite.fragment = "res/sprite.f.glsl"
sprite.vertex = "res/sprite.v.glsl"
